In [1]:
import numpy as np
num = np.array([10,20,30,40,50])

In [2]:
num

array([10, 20, 30, 40, 50])

In [3]:
type(num)

numpy.ndarray

In [4]:
num2 = np.array([[1,2,3],[4,5,6]])
num2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
floats = np.array([0.2,0.5,0.6,0.8,0.9])
floats

array([0.2, 0.5, 0.6, 0.8, 0.9])

In [6]:
type(floats)

numpy.ndarray

In [7]:
num.ndim

1

In [8]:
num2.ndim

2

In [9]:
num.size  #no of elements

5

In [11]:
num.itemsize #no of bytes

4

In [12]:
#iterating though multi-dimensional array
for r in num2:
    for c in r:
        print(c,end=" ")
    print()    

1 2 3 
4 5 6 


In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.full((4,4),15)

array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]])

##### Creating arrays from Ranges

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [20]:
np.arange(20,1,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [23]:
np.linspace(0.0,0.2,num=10) #linspace produces evenly spaced floating-point ranges

array([0.        , 0.02222222, 0.04444444, 0.06666667, 0.08888889,
       0.11111111, 0.13333333, 0.15555556, 0.17777778, 0.2       ])

In [24]:
#Reshaping arrays
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
num3 = np.arange(1,6)
num3

array([1, 2, 3, 4, 5])

In [27]:
num3*2

array([ 2,  4,  6,  8, 10])

In [28]:
num3**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [29]:
num3 # num3 is not changed

array([1, 2, 3, 4, 5])

In [30]:
num3+=10
num3

array([11, 12, 13, 14, 15])

In [31]:
num3

array([11, 12, 13, 14, 15])

In [34]:
num3 * [2,2,3,2,4] #broadcasting

array([22, 24, 39, 28, 60])

In [35]:
num3

array([11, 12, 13, 14, 15])

In [36]:
num3 >= 12

array([False,  True,  True,  True,  True])

In [38]:
num4 = np.array([10,12,13,19,20])
num4

array([10, 12, 13, 19, 20])

In [39]:
num3 == num4

array([False,  True,  True, False, False])

##### NumPy Calculation Methods

In [40]:
grades =np.array([[87,96,80],[100,89,90],
                  [94,96,90],[100,91,92]])
grades

array([[ 87,  96,  80],
       [100,  89,  90],
       [ 94,  96,  90],
       [100,  91,  92]])

In [41]:
grades.sum()

1105

In [42]:
grades.mean()

92.08333333333333

In [43]:
grades.min()

80

In [44]:
grades.max()

100

In [45]:
grades.std()

5.407684860969208

In [46]:
grades.var()

29.243055555555557

In [47]:
grades.mean(axis=0) # 0 represents row

array([95.25, 93.  , 88.  ])

In [49]:
grades.mean(axis=1) # 1 represents column

array([87.66666667, 93.        , 93.33333333, 94.33333333])

##### Universal Functions 

In [59]:
num5 = np.array([1,2,3,4,5,6])
num6 = np.array([100,200,300,500,600,700])

In [60]:
np.sqrt(num6)

array([10.        , 14.14213562, 17.32050808, 22.36067977, 24.49489743,
       26.45751311])

In [61]:
np.add(num5,num6)

array([101, 202, 303, 504, 605, 706])

In [62]:
np.multiply(num5,5)

array([ 5, 10, 15, 20, 25, 30])

In [66]:
num6 = num5.reshape(2,3)
num6

array([[1, 2, 3],
       [4, 5, 6]])

##### Indexing and Slicing

In [70]:
grades =np.array([[87,96,80],[100,89,90],
                  [94,96,90],[100,91,92]])
grades

array([[ 87,  96,  80],
       [100,  89,  90],
       [ 94,  96,  90],
       [100,  91,  92]])

In [71]:
grades[0,1]

96

In [73]:
grades[0:2] #select sequential rows

array([[ 87,  96,  80],
       [100,  89,  90]])

In [75]:
grades[[1,3]] # select non-sequential rows

array([[100,  89,  90],
       [100,  91,  92]])

In [79]:
grades[:,2] #select only elements in lst column

array([80, 90, 90, 92])

In [81]:
grades[:,1:3] #selecting consecutive columns using slice

array([[96, 80],
       [89, 90],
       [96, 90],
       [91, 92]])

In [82]:
grades[:,[0,2]] #selectin non-consecutive columns using slice

array([[ 87,  80],
       [100,  90],
       [ 94,  90],
       [100,  92]])

##### Views - Shallow Copy

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [3]:
numbers1 = numbers.view()
numbers1

array([1, 2, 3, 4, 5])

In [4]:
id(numbers)

1810895998768

In [6]:
id(numbers1)

1810895998864

In [7]:
numbers[1]*=10

In [8]:
numbers

array([ 1, 20,  3,  4,  5])

In [10]:
numbers1

array([ 1, 20,  3,  4,  5])

In [11]:
numbers1[3]+=100

In [12]:
numbers1

array([  1,  20,   3, 104,   5])

In [13]:
numbers

array([  1,  20,   3, 104,   5])

In [14]:
numbers2 = numbers[0:3] #slicing also creates view

In [15]:
numbers2

array([ 1, 20,  3])

In [16]:
numbers[1]/=2

In [17]:
numbers

array([  1,  10,   3, 104,   5])

In [18]:
numbers2

array([ 1, 10,  3])

##### Deep Copy

In [20]:
numb = np.arange(1,8)

In [21]:
numb

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
numb_deep_copy = numb.copy()
numb_deep_copy

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
numb[5]*=5
numb

array([ 1,  2,  3,  4,  5, 30,  7])

In [24]:
numb_deep_copy

array([1, 2, 3, 4, 5, 6, 7])

##### Reshaping and Transposing

In [25]:
marks =np.array([[87,96,80],[100,89,90]])
marks

array([[ 87,  96,  80],
       [100,  89,  90]])

In [28]:
marks.reshape(1,6)  #reshape does not modify original

array([[ 87,  96,  80, 100,  89,  90]])

In [29]:
marks

array([[ 87,  96,  80],
       [100,  89,  90]])

In [30]:
marks1 =np.array([[87,96,80],[100,89,90]])
marks1

array([[ 87,  96,  80],
       [100,  89,  90]])

In [32]:
marks1.resize(1,6)
marks1

array([[ 87,  96,  80, 100,  89,  90]])

##### flatten Vs ravel

In [33]:
f = np.array([[87,96,80],[100,89,90]]) 
flat = f.flatten()  #flatten does not share dat with original
flat

array([ 87,  96,  80, 100,  89,  90])

In [34]:
f

array([[ 87,  96,  80],
       [100,  89,  90]])

In [35]:
r = np.array([[87,96,80],[100,89,90]]) 
r

array([[ 87,  96,  80],
       [100,  89,  90]])

In [36]:
ra = r.ravel()
ra

array([ 87,  96,  80, 100,  89,  90])

In [37]:
r

array([[ 87,  96,  80],
       [100,  89,  90]])

In [38]:
ra[4]*=5
ra

array([ 87,  96,  80, 100, 445,  90])

In [39]:
r

array([[ 87,  96,  80],
       [100, 445,  90]])

##### Transpose columns and rows

In [42]:
result = np.array([[ 87,  96,  80],
       [100,  89,  90]])
result

array([[ 87,  96,  80],
       [100,  89,  90]])

In [43]:
result.T

array([[ 87, 100],
       [ 96,  89],
       [ 80,  90]])

##### Horizontal and Vertical stacking

In [44]:
p = np.array([[87,96,80],[100,89,90]]) 
q = np.array([[94,96,90],[100,91,92]])

In [45]:
np.hstack((p,q))

array([[ 87,  96,  80,  94,  96,  90],
       [100,  89,  90, 100,  91,  92]])

In [46]:
np.vstack((p,q))

array([[ 87,  96,  80],
       [100,  89,  90],
       [ 94,  96,  90],
       [100,  91,  92]])