In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.0.3'

In [3]:
ds = pd.Series([10,30,56,89,39,76])
print(ds)

0    10
1    30
2    56
3    89
4    39
5    76
dtype: int64


In [4]:
print(ds.keys)

<bound method Series.keys of 0    10
1    30
2    56
3    89
4    39
5    76
dtype: int64>


In [5]:
print(ds.values)

[10 30 56 89 39 76]


In [6]:
print(ds.index)

RangeIndex(start=0, stop=6, step=1)


In [7]:
print(ds.agg(['min','max','sum','mean','std']))

min      10.000000
max      89.000000
sum     300.000000
mean     50.000000
std      29.509321
dtype: float64


In [8]:
print(ds[1])
print(ds[1:4])
print(ds[1:6:2])

30
1    30
2    56
3    89
dtype: int64
1    30
3    89
5    76
dtype: int64


In [9]:
data1 = pd.Series([1,2,3,4],index=['a','b','c','d'])
data2 = pd.Series({'a':1,'b':2,'c':3,'d':4})
data1

a    1
b    2
c    3
d    4
dtype: int64

In [10]:
data2

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
print(data2['c'])

3


In [12]:
import pandas as pd
import numpy as np
myarray = np.array([[6,9,8,5,4,2],[0,2,5,6,3,9],
[8,5,4,1,2,3],[6,9,8,5,4,2],
[0,5,3,6,9,8],[8,7,4,5,2,3]])
row_names = ['a', 'b','c','d','e','f']
col_names = ['one', 'two', 'three','four','five','six']
df = pd.DataFrame(myarray, index=row_names, columns=col_names)
print(df)

   one  two  three  four  five  six
a    6    9      8     5     4    2
b    0    2      5     6     3    9
c    8    5      4     1     2    3
d    6    9      8     5     4    2
e    0    5      3     6     9    8
f    8    7      4     5     2    3


In [13]:
myarray

array([[6, 9, 8, 5, 4, 2],
       [0, 2, 5, 6, 3, 9],
       [8, 5, 4, 1, 2, 3],
       [6, 9, 8, 5, 4, 2],
       [0, 5, 3, 6, 9, 8],
       [8, 7, 4, 5, 2, 3]])

In [14]:
data_list = [['A',10,'X'],['B',20,'Y'],['C',30,'Z'],['D',40,'K']]
columns = ['Name','Age','Job']
data3 = pd.DataFrame(data_list,columns=columns)
data3

Name  Age Job
0    A   10   X
1    B   20   Y
2    C   30   Z
3    D   40   K

In [15]:
x = pd.Series({'a':10,'b':20,'c':30})
y = pd.Series({'a':40,'b':50,'c':60})
z = pd.Series({'a':70,'b':80,'c':90})
m = pd.DataFrame({'AA':x,'BB':y,'CC':z})
x.keys

<bound method Series.keys of a    10
b    20
c    30
dtype: int64>

In [16]:
x.values

array([10, 20, 30], dtype=int64)

In [17]:
x


a    10
b    20
c    30
dtype: int64

In [18]:
data1 = pd.Index([1,2,3,4,5])
data2 = pd.Index([9,8,7,6,5])
row_names = ['First','Second','Third','Fourth','Fifth']
d1 = pd.DataFrame({'c1':data1,'c2':data2},index=row_names)
d1

c1  c2
First    1   9
Second   2   8
Third    3   7
Fourth   4   6
Fifth    5   5

In [19]:
data = [{'square':i**2} for i in range(10)]
df = pd.DataFrame(data)
df

square
0       0
1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81

In [20]:
data = [{'square':i**2,'cube':i**3,'sqrt':i**0.5} for i in range(10)]
df1 = pd.DataFrame(data)
df1

square  cube      sqrt
0       0     0  0.000000
1       1     1  1.000000
2       4     8  1.414214
3       9    27  1.732051
4      16    64  2.000000
5      25   125  2.236068
6      36   216  2.449490
7      49   343  2.645751
8      64   512  2.828427
9      81   729  3.000000

In [21]:
df3 = pd.DataFrame(np.random.rand(3,2),columns=['food','drink'],index=['a','b','c'])
df3

food     drink
a  0.532435  0.364282
b  0.262538  0.230528
c  0.494775  0.307087

In [22]:
import pandas as pd
w = pd.Series({'a':1 ,'b':2 ,'c':3 ,'d':4 ,'e':5})
x = pd.Series({'a':6 ,'b':7 ,'c':8 ,'d':9 ,'e':10})
y = pd.Series({'a':11 ,'b':12 ,'c':13 ,'d':14 ,'e':15})
z = pd.Series({'a':16 ,'b':17 ,'c':18 ,'d':19 ,'e':20})
grades = pd.DataFrame({'Math':w,'Physics':x,'French':y,'Chemistry':z})
grades.keys()

Index(['Math', 'Physics', 'French', 'Chemistry'], dtype='object')

In [23]:
grades.values

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]], dtype=int64)

In [24]:
grades.values.T

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int64)

In [25]:
grades.columns

Index(['Math', 'Physics', 'French', 'Chemistry'], dtype='object')

In [26]:
'Math' in grades.keys()

True

In [27]:
'English' in grades.keys()

False

In [28]:
18 in grades.values

True

In [29]:
100 in grades.values

False

In [30]:
grades

Math  Physics  French  Chemistry
a     1        6      11         16
b     2        7      12         17
c     3        8      13         18
d     4        9      14         19
e     5       10      15         20

In [31]:
grades.stack()

a  Math          1
   Physics       6
   French       11
   Chemistry    16
b  Math          2
   Physics       7
   French       12
   Chemistry    17
c  Math          3
   Physics       8
   French       13
   Chemistry    18
d  Math          4
   Physics       9
   French       14
   Chemistry    19
e  Math          5
   Physics      10
   French       15
   Chemistry    20
dtype: int64

In [32]:
grades.iloc[:3,:2]

Math  Physics
a     1        6
b     2        7
c     3        8

In [38]:
grades.loc['b':'c',['Math','Physics']]

Math  Physics
b     2        7
c     3        8

In [34]:
grades.loc[grades.Math > 3]

Math  Physics  French  Chemistry
d     4        9      14         19
e     5       10      15         20

In [35]:
grades.loc[grades.Math > 3,['Physics','Math']]

Physics  Math
d        9     4
e       10     5

In [36]:
import pandas as pd
w = pd.Series({'a':1 ,'b':2 ,'c':3 ,'d':4 ,'e':5})
x = pd.Series({'a':6 ,'b':7 ,'c':8 ,'d':9 ,'e':10})
y = pd.Series({'a':11 ,'b':12 ,'c':13 ,'d':14 ,'e':15})
z = pd.Series({'a':16 ,'b':17 ,'c':18 ,'d':19 ,'e':20})
grades = pd.DataFrame({'Math':w,'Physics':x,'French':y,'Chemistry':z})
grades

Math  Physics  French  Chemistry
a     1        6      11         16
b     2        7      12         17
c     3        8      13         18
d     4        9      14         19
e     5       10      15         20

In [41]:
grades.sort_values(['Math'],ascending=False)


Math  Physics  French  Chemistry
e     5       10      15         20
d     4        9      14         19
c     3        8      13         18
b     2        7      12         17
a     1        6      11         16

In [42]:
grades.sort_values(['Chemistry'],ascending=True)

Math  Physics  French  Chemistry
a     1        6      11         16
b     2        7      12         17
c     3        8      13         18
d     4        9      14         19
e     5       10      15         20

In [43]:
grades.corr()

Math  Physics  French  Chemistry
Math        1.0      1.0     1.0        1.0
Physics     1.0      1.0     1.0        1.0
French      1.0      1.0     1.0        1.0
Chemistry   1.0      1.0     1.0        1.0

In [44]:
df = pd.DataFrame(np.random.rand(5, 3), columns=['A', 'B', 'C'])
df

A         B         C
0  0.299572  0.827491  0.157389
1  0.679177  0.623530  0.655931
2  0.336258  0.557308  0.053365
3  0.436113  0.892183  0.815744
4  0.763496  0.065792  0.887617

In [45]:
df.corr()

A         B         C
A  1.000000 -0.715633  0.788125
B -0.715633  1.000000 -0.338681
C  0.788125 -0.338681  1.000000

In [46]:
df.skew(0)

A    0.457181
B   -1.291442
C   -0.445726
dtype: float64

In [49]:
df1 = pd.DataFrame(
{
"A": ["A0", "A1", "A2", "A3"],
"B": ["B0", "B1", "B2", "B3"],
"C": ["C0", "C1", "C2", "C3"],
"D": ["D0", "D1", "D2", "D3"],
},
index=[0, 1, 2, 3],
)
df2 = pd.DataFrame(
{
"A": ["A4", "A5", "A6", "A7"],
"B": ["B4", "B5", "B6", "B7"],
"C": ["C4", "C5", "C6", "C7"],
"D": ["D4", "D5", "D6", "D7"],
},
index=[4, 5, 6, 7],
)
df3 = pd.DataFrame(
{
"A": ["A8", "A9", "A10", "A11"],
"B": ["B8", "B9", "B10", "B11"],
"C": ["C8", "C9", "C10", "C11"],
"D": ["D8", "D9", "D10", "D11"],
},
    index=[8, 9, 10, 11],
)
frames = [df1, df2, df3]
result = pd.concat(frames)
result


A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [51]:
result = pd.concat(frames,keys=['x','y','z'])
result

A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11

In [52]:
df4 = pd.DataFrame(
{
"B": ["B2", "B3", "B6", "B7"],
"D": ["D2", "D3", "D6", "D7"],
"F": ["F2", "F3", "F6", "F7"],
},
index=[2, 3, 6, 7],
)
df4

B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

In [53]:
r1 = pd.concat([df1,df4],axis=1)
r1

A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [55]:
r2 = pd.concat([df1,df4],join='inner',axis=1)
r2

A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

In [56]:
r3 = pd.concat([df1,df4],ignore_index=True,sort=False)
r3

A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [59]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering',
'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})
print(df1)
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [60]:
df3 = pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [61]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
'supervisor': ['Carly', 'Guido', 'Steve']})
df5 = pd.merge(df3,df4)
df5

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [73]:
import pandas as pd
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering','Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'salary': [70000, 80000, 120000, 90000]})
r4 = pd.merge(df1,df3,left_on='employee',right_on='name')
r4

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [65]:
pd.merge(df1,df3,left_on='employee',right_on='name').drop('name',axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [68]:
df1 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
'food': ['fish', 'beans', 'bread']},
columns=['name', 'food'])
df2 = pd.DataFrame({'name': ['Mary', 'Joseph'],
'drink': ['cola', '7 up']},
columns=['name', 'drink'])
r5 = pd.merge(df1,df2)
r5

name   food drink
0  Mary  bread  cola

In [69]:
r6 = pd.merge(df1,df2,how='inner')
r6

name   food drink
0  Mary  bread  cola

In [75]:
df1 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
'food': ['fish', 'beans', 'bread']},
columns=['name', 'food'])
df2 = pd.DataFrame({'name': ['Mary', 'Joseph'],
'drink': ['cola', '7 up']},
columns=['name', 'drink'])
r7 = pd.merge(df1,df2,how='outer')
r7

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  cola
3  Joseph    NaN  7 up

In [78]:
index = [('California', 2000),('California', 2010),('New York', 2000),('New York', 2010),('Texas', 2000),('Texas', 2010)]
populations = [10000,15000,20000,25000,30000,35000]
index = pd.MultiIndex.from_tuples(index)
pop = pd.Series(populations,index=index)
pop

California  2000    10000
            2010    15000
New York    2000    20000
            2010    25000
Texas       2000    30000
            2010    35000
dtype: int64

In [83]:
df = pd.DataFrame(np.random.rand(4, 2),index=[['a','a','b','b'],[1,2,1,2]],columns=['income','profit'])
df

income    profit
a 1  0.594764  0.579010
  2  0.527722  0.078440
b 1  0.166991  0.871747
  2  0.503901  0.921811

In [84]:
x = pd.to_datetime('1st of January,2024')
x

Timestamp('2024-01-01 00:00:00')

In [86]:
y = x + pd.to_timedelta(np.arange(20),'D')
z = x - pd.to_timedelta(np.arange(20),'D')
print(x)
print(y)
print(z)

2024-01-01 00:00:00
DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12',
               '2024-01-13', '2024-01-14', '2024-01-15', '2024-01-16',
               '2024-01-17', '2024-01-18', '2024-01-19', '2024-01-20'],
              dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2024-01-01', '2023-12-31', '2023-12-30', '2023-12-29',
               '2023-12-28', '2023-12-27', '2023-12-26', '2023-12-25',
               '2023-12-24', '2023-12-23', '2023-12-22', '2023-12-21',
               '2023-12-20', '2023-12-19', '2023-12-18', '2023-12-17',
               '2023-12-16', '2023-12-15', '2023-12-14', '2023-12-13'],
              dtype='datetime64[ns]', freq=None)


In [87]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04','2015-07-04','2015-08-04'])
data = pd.Series([0, 1, 2, 3], index=index)
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [89]:
dr = pd.date_range('01-JAN-24','15-JAN-24')
dr

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12',
               '2024-01-13', '2024-01-14', '2024-01-15'],
              dtype='datetime64[ns]', freq='D')

In [93]:
dr = pd.date_range('01-JAN-24',periods=12,freq='H')
dr

DatetimeIndex(['2024-01-01 00:00:00', '2024-01-01 01:00:00',
               '2024-01-01 02:00:00', '2024-01-01 03:00:00',
               '2024-01-01 04:00:00', '2024-01-01 05:00:00',
               '2024-01-01 06:00:00', '2024-01-01 07:00:00',
               '2024-01-01 08:00:00', '2024-01-01 09:00:00',
               '2024-01-01 10:00:00', '2024-01-01 11:00:00'],
              dtype='datetime64[ns]', freq='H')